version: "3.8"

services:
  server:
    container_name: server
    build:
      context: ./apps/server
      target: dev
    volumes:
      - ./apps/server/:/usr/src/app
    ports:
      - "8080:8080"